language: python
python:
  - "3.6.4"
  - "2.7.14"
  - "3.5.5"
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt six
# command to run tests
script:
  - export PYTHONPATH="$PWD" && cd tests/ && ./run.py
